apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: demo-deployment
  name: demo-deployment
  namespace: ashhad-demo
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: demo-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: demo-deployment
    spec:
      containers:
      - image: ashhadulislamdocker/demo_image
        imagePullPolicy: IfNotPresent
        name: demo-deployment
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30